

utility-payment:
  ribbon:
    eureka:
      enabled: true
  url: http://utility-payment

zuul:
  routes:
    paymentGroups:
      path: /tbcibs-play/**/paymentGroups
      strip-prefix: true
      serviceId: utility-payment
    paymentRegions:
      path: /tbcibs-play/**/paymentRegions
      serviceId: utility-payment
    legacy:
      sensitiveHeaders:
      path: /tbcibs-play/**
      strip-prefix: true
      url: http://localhost:8090
    legacy-ui:
       path: /tbcibs.server.angular/**
       strip-prefix: false
       url: http://10.2.11.13:9082

server:
  port: 8081




